### ISSUE TITLE
Changes following on from the initial psykal version created in #3

### ISSUE THREAD

**Issue by rupertford** [arporter/NEMO-DSL#4]
In #3, separate kernels were created for each loop in the original code. A few issues have arisen before the psykal version can be taken any further.

1) Are we OK to move the zdt and zbtr scalars out of the algorithm later and into the associated Kernels? We can clearly do this as they are only scalars but Silvia had them at a higher level in the loops for some reason so I would like her thoughts first.

2) Are we working towards a version that PSyclone can generate? The alternative is to explore ways in writing the psykal code that might be more amenable to the NEMO consortium? I lean to the former as it would be nice to be able to demonstrate something (at some point).

3) I've introduced two builtins which set layer values. In order to do this they must pass the actual value of the layer. What I suggest is that we have a zero_top_layer() and a zero_bottom_layer() (and similarly for multiply) as these would be descriptive, explanatory and would remove the need for passing the layer value, which we need to move away from.

4) We should remove the passing of jpk, jpk and jpi into the PSy layer from the algorithm layer as the algorithm layer is meant to work on whole fields and it also simplified the code. To do this in the short term I was going to set the values in the PSy layer directly from the algorithm layer. Are you OK with this, or is there a better way.

5) Are people happy that I'm only looking at code with the iteration at the moment. I'm not sure how this will work if we decide to change to field objects but we can cross that bridge later.

6) We already have an interesting issue emerging with the vertical dimension. The setting of top and bottom values means that we sometimes do not compute at the bottom layer and/or the top layer. I don't think this is anything to do with the Kernel code so I presume we will have to find a way to describe this at the algorithm layer!

7) The zwx2_kern kernel code writes with a k+1 index. In PSylone we made a choice to always write to I,j,k to help us work out the correct loop bounds. Is there a problem in changing the code to conform to this choice?

OK, that's enough for the moment. Agreement on these questions will drive the next set of modifications to the psykal version.

**Comment by smocavero** [comment]
Answer to some questions:

Q1. In the original version of the NEMO routine, the two scalars are updated at each outer loop iteration by using the vertical profile of tracer time-step (which changes depending on the vertical level). I simplified the update in order to limit the number of arrays handled within the kernel, then the operation seems to have no much sense. I agree to move the scalars out of the algorithm. I think that the main goal at this stage is not to reproduce the same operations peformed by the original code but to demonstrate that NEMO rewrite by using PSyclone approach is feasible.

Q2. I agree. We have a limited time within the IS-ENES2 project and I would suggest to use it to demonstrate something (as you said).

A general comment on loop bounds: we can change the zwx2 kernel code to match the choice in PSyclone. However, if we want to ensure the same behavior of the code w.r.t. the original NEMO code, we should change the scalars computation within the zwx2 kernel. This is not relevant at this stage, but in the future we have to consider that the NEMO code sometimes iterates up to k-1 and writes on k and k+1.

**Comment by arporter** [comment]
My thoughts:

Q2. I agree with Rupert and Silvia - let's have something to demonstrate (on the proviso that the code that we end up with won't scare-off the NEMO developers - first impressions are important)

Q3. I like your 'layer' built-ins and think that specialising them to 'top' and 'bottom' is a good idea. Actually, in light of my response to Qs 6 & 7 (see below) maybe these are really boundary-condition routines.

Q4. Yes, for the moment I would just add some `init` routine to the psy layer and set them there. We can change this once we have some infrastructure up and running.

Q5. I don't understand this question...

Q6 and 7. It looks to me as though these two issues essentially boil-down to identifying the access pattern (stencil?) in z. I would favour sticking with writing to `(ji,jj,jk)` within a kernel so as to reduce the chance of confusion. I'm not totally sure that whether or not a kernel computes at the surface/bottom is always an issue for the Algorithm layer. I can imagine having a kernel that simply cannot be applied to the bottom layer (e.g. it writes to `jk` but reads from `jk+1`). This would then have to be captured in meta-data (maybe by extending the GOcean2d concept of ITERATES_OVER to 3D). In fact, this is the same problem faced by a kernel applying some horizontal stencil when it comes to the horizontal boundaries of the domain.

**Comment by rupertford** [comment]
OK, I'm clear on questions 1 to 4.

Question 5 was badly explained, apologies. I was just pointing out that, at the moment, I am only looking at code within the iteration loop, i.e. I have not PSyKAl'ed initialisation (and finalisation) code. I was checking that people were OK with this approach for the timebeing and was saying that we might want/need to revisit this if we are going to end up with a field-object solution in the algorithm layer.

Question 6. I agree that we can infer the bounds due to the stencil access in the vertical and that it makes sense to capture this in the kernel metadata as we do for the horizontal. I think I also agree that the xero'ing and top and bottom are essentially boundary conditions. However, if we take the boundary condition approach with no information in the algorithm layer then I think that in some cases we will end up performing computation at the top and/or bottom layer in a Kernel that we subsequently zero with our boundary condition calls. That is OK, it will give us correct results and is consistent with the current PSyclone implementation, but it would be different to what is done in Silvia's original benchmark and would involve more computation and (probably) more memory traffic. Actually, we should be able to work out minimal loop bounds in the presence of boundary condition computation using algorithm layer dependence analysis, so I think I've convinced myself that the as-is PSyclone approach is the way to go.

Question 7, I think we have agreed on this i.e. we will modify kernels to write to (ji,jj,jk) where appropriate.

**Comment by arporter** [comment]
Q5. Ah, I see. Yes, I think what you've done is fine for the moment. We can tidy things up once the infrastructure is in place.

**Comment by rupertford** [comment]
OK, I think we have agreed on the next set of PSyKAl changes so I will implement these as part of this issue.

**Comment by rupertford** [comment]
Created psykal-part-2 branch

**Comment by rupertford** [comment]
Q1. Removed scalars as agreed. I accidentally tagged the commits with issue #3 rather than #4 so they won't appear here. Apologies.

**Comment by rupertford** [comment]
Q4. (first step) algorithm layer now passes loop bounds to the PSy layer and the PSy layer stores them. This means we will no longer need to pass the bounds though every call.
Q3 replaced zero_layer with  zero_top_layer and zero_bottom_layer. replaced multiply_layer with multiply_bottom_layer. These routines now only pass the full field from the algorithm layer and do not pass loop bounds.

**Comment by rupertford** [comment]
Q4. jpi,jpj and jpk are no longer passed into the PSy layer via the argument list when calling the PSy layer.

**Comment by rupertford** [comment]
Modified zwx2_kern so that it writes to zwx as I,j,k and not I,j,k+1. I needed to modify the psy loop bound appropriately.

**Comment by rupertford** [comment]
I think I've covered all the changes so am going to make a pull request. I'm not sure what else needs to be done before Andy integrates this into the existing gocean infrastructure.

I guess the big question is whether we turn arrays into field objects or not. I can't see how we would use Andy's infrastructure without doing this, but perhaps there is a way.

A lesser outstanding question is whether any of the masks should only exist in the PSy layer, or whether they should all be passed in.

There is also the outstanding issue of looping from 1..jpk and then doing boundary conditions vs looping from 1..jpk-1 as we know jpk is a boundary condition update. I think PSyclone will need to do the former (but cold be optimized with analysis) but the original code does the latter. This will mean moving the boundary condition calls over the compute call in at least one location.

**Comment by rupertford** [comment]
pull request #6 is now on master so I am closing this issue.
